/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym.bca;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author KRATOS
 */
public class customer1 extends javax.swing.JFrame {
Connection co=null;
ResultSet rs=null;
PreparedStatement ps=null;
    private String sql4;
    private Object date1;
    /**
     * Creates new form customer1
     */
    public customer1() {
        initComponents();
        co=Mysqlconnect.MysqlDB();
    }
    public void close(){
        WindowEvent w=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
          Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(w);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c_fname = new javax.swing.JTextField();
        c_mname = new javax.swing.JTextField();
        c_lname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        sav = new javax.swing.JButton();
        cont_num = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        weg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hig = new javax.swing.JTextField();
        can1 = new javax.swing.JButton();
        genderr = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rec1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        date2 = new com.toedter.calendar.JDateChooser();
        date11 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/bca/P_4.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 950, 110);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("RECEIPT NUMBER");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 65, 200, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CUSTOMER NAME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 103, 200, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("GENDER");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 141, 200, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CONTACT NUMBER");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 179, 200, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DURATION");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 217, 200, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("AGE");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 255, 200, 25);

        c_fname.setToolTipText("CUSTOMER FIRST NAME");
        jPanel2.add(c_fname);
        c_fname.setBounds(248, 103, 150, 25);

        c_mname.setToolTipText("CUSTOMER MIDDLE NAME");
        jPanel2.add(c_mname);
        c_mname.setBounds(416, 103, 150, 25);

        c_lname.setToolTipText("CUSTOMER LAST NAME");
        jPanel2.add(c_lname);
        c_lname.setBounds(584, 103, 150, 25);

        age.setToolTipText("CUSTOMER AGE");
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });
        jPanel2.add(age);
        age.setBounds(248, 255, 150, 25);

        sav.setText("SAVE");
        sav.setBorder(null);
        sav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savActionPerformed(evt);
            }
        });
        jPanel2.add(sav);
        sav.setBounds(270, 390, 100, 21);

        cont_num.setToolTipText("CUSTOMER CONTACT NUMBER");
        cont_num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cont_numKeyTyped(evt);
            }
        });
        jPanel2.add(cont_num);
        cont_num.setBounds(248, 179, 200, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("WEIGHT");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 293, 200, 25);

        weg.setToolTipText("Kg.\n");
        weg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                wegKeyTyped(evt);
            }
        });
        jPanel2.add(weg);
        weg.setBounds(248, 293, 150, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("HEIGHT");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 331, 200, 25);

        hig.setToolTipText("Inch");
        hig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                higKeyTyped(evt);
            }
        });
        jPanel2.add(hig);
        hig.setBounds(248, 331, 150, 25);

        can1.setText("CANCEL");
        can1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                can1ActionPerformed(evt);
            }
        });
        jPanel2.add(can1);
        can1.setBounds(470, 390, 100, 20);

        genderr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderr.setToolTipText("CUSTOMER GENDER");
        jPanel2.add(genderr);
        genderr.setBounds(250, 140, 150, 25);

        jLabel12.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("                 CUSTOMER DETAILS");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel12);
        jLabel12.setBounds(270, 0, 400, 35);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/bca/D_4.jpg"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 0, 190, 500);
        jPanel2.add(rec1);
        rec1.setBounds(250, 65, 156, 22);

        jLabel7.setText("TO");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(420, 220, 30, 25);

        date2.setDateFormatString("YYYY-MM-DD");
        jPanel2.add(date2);
        date2.setBounds(460, 220, 150, 25);

        date11.setDateFormatString("YYYY-MM-DD");
        jPanel2.add(date11);
        date11.setBounds(250, 220, 150, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void can1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_can1ActionPerformed
        // TODO add your handling code here:
       int a;
    a = JOptionPane.showConfirmDialog(null, "Do You Really Want to Cancle","Cancle",JOptionPane.YES_NO_OPTION);
    if(a==0){
        close();
        home h=new home();
       h.setVisible(true);
    }
    }//GEN-LAST:event_can1ActionPerformed

    private void savActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savActionPerformed
        
            String datee1=((JTextField)date11.getDateEditor().getUiComponent()).getText();
              String datee2=((JTextField)date2.getDateEditor().getUiComponent()).getText();
              String gen=(String) genderr.getSelectedItem();
              String s=cont_num.getText();
              //Int a=Integer
              
        try{
          //if(s>)
               int a;
    a = JOptionPane.showConfirmDialog(null, "Do You Really Want to SAVE","SAVED",JOptionPane.YES_NO_OPTION);
    if(a==0){
              String sql="insert into customer_details (receipt_number,first_name,middle_name,last_name,gender,contact_number,date_1,date_2,age,weight,hight) values (?,?,?,?,?,?,?,?,?,?,?)";
           
            //  String sql="insert into customer_details (receipt_number,first_name,middle_name,last_name,gender,contact_number,date_1,date_2,age,weight,hight) values (?,?,?,?,?,?,?,?,?,?,?)";
             
            ps=co.prepareStatement(sql);
            ps.setString(1, rec1.getText());
            ps.setString(2, c_fname.getText());
            ps.setString(3, c_mname.getText());
            ps.setString(4, c_lname.getText());
            ps.setString(5, gen);
            ps.setString(6, cont_num.getText());
           // ps.setString(7, date_1.getText());
           ps.setString(7, datee1);
            ps.setString(8, datee2);
          // ps.setString(8, date_2.getText());
            ps.setString(9, age.getText());
            ps.setString(10, weg.getText());
            ps.setString(11, hig.getText());
            ps.execute();
          JOptionPane.showMessageDialog(null, "SAVED");
        }}
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
       
        
        
        payment p=new payment();
       p.rec_num3.setText(rec1.getText());
       p.c_fname3.setText(c_fname.getText());
       p.c_mname3.setText(c_mname.getText());
       p.c_lname3.setText(c_lname.getText());
       p.con_num3.setText(cont_num.getText());
        p.setVisible(true);
        close();
    }//GEN-LAST:event_savActionPerformed

    private void cont_numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cont_numKeyTyped
        // TODO add your handling code here:
       char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_cont_numKeyTyped

    private void date_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date_1KeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_date_1KeyTyped

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_ageKeyTyped

    private void wegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wegKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_wegKeyTyped

    private void higKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_higKeyTyped
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_higKeyTyped

    private void date_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField age;
    public static javax.swing.JTextField c_fname;
    public static javax.swing.JTextField c_lname;
    public static javax.swing.JTextField c_mname;
    private javax.swing.JButton can1;
    public static javax.swing.JTextField cont_num;
    public static com.toedter.calendar.JDateChooser date11;
    public static com.toedter.calendar.JDateChooser date2;
    private javax.swing.Box.Filler filler1;
    public static javax.swing.JComboBox<String> genderr;
    public static javax.swing.JTextField hig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField rec1;
    private javax.swing.JButton sav;
    public static javax.swing.JTextField weg;
    // End of variables declaration//GEN-END:variables

}

