/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym.bca;

import com.sun.glass.events.KeyEvent;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author KRATOS
 */
public class Customer2 extends javax.swing.JFrame {

    Connection co = null;
    ResultSet rs = null;
    PreparedStatement ps = null;

    /**
     * Creates new form Customer2
     */
    public Customer2() {
        initComponents();
        co = Mysqlconnect.MysqlDB();
    }
    public void close(){
        WindowEvent w=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
          Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(w);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rec_num2 = new javax.swing.JTextField();
        c_fname2 = new javax.swing.JTextField();
        c_mname2 = new javax.swing.JTextField();
        c_lname2 = new javax.swing.JTextField();
        con_num2 = new javax.swing.JTextField();
        age2 = new javax.swing.JTextField();
        weh2 = new javax.swing.JTextField();
        hig2 = new javax.swing.JTextField();
        upa = new javax.swing.JButton();
        can2 = new javax.swing.JButton();
        genderr1 = new javax.swing.JComboBox<>();
        del = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/bca/P_10.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 950, 110);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("RECEIPT NUMBER");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(47, 65, 200, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CUSTOMER NAME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(47, 103, 200, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("GENDER");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(47, 142, 200, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CONTACT NUMBER");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(47, 182, 200, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DURATION");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(47, 220, 200, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("AGE");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(47, 258, 200, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("WEIGHT");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(47, 296, 200, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("HEIGHT");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(47, 334, 200, 25);

        rec_num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rec_num2ActionPerformed(evt);
            }
        });
        rec_num2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rec_num2KeyTyped(evt);
            }
        });
        jPanel2.add(rec_num2);
        rec_num2.setBounds(277, 65, 150, 25);

        c_fname2.setToolTipText("CUSTOMER FIRST NAME");
        jPanel2.add(c_fname2);
        c_fname2.setBounds(277, 103, 150, 25);

        c_mname2.setToolTipText("CUSTOMER MIDDLE NAME");
        jPanel2.add(c_mname2);
        c_mname2.setBounds(437, 103, 150, 25);

        c_lname2.setToolTipText("CUSTOMER LAST NAME");
        c_lname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_lname2ActionPerformed(evt);
            }
        });
        jPanel2.add(c_lname2);
        c_lname2.setBounds(597, 103, 150, 25);

        con_num2.setToolTipText("CUSTOMER CONTACT NUMBER");
        con_num2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                con_num2KeyTyped(evt);
            }
        });
        jPanel2.add(con_num2);
        con_num2.setBounds(277, 182, 200, 25);

        age2.setToolTipText("CUSTOMER AGE");
        age2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                age2KeyTyped(evt);
            }
        });
        jPanel2.add(age2);
        age2.setBounds(277, 258, 150, 25);

        weh2.setToolTipText("Kg.");
        weh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weh2ActionPerformed(evt);
            }
        });
        weh2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                weh2KeyTyped(evt);
            }
        });
        jPanel2.add(weh2);
        weh2.setBounds(277, 296, 150, 25);

        hig2.setToolTipText("Inch");
        hig2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hig2KeyTyped(evt);
            }
        });
        jPanel2.add(hig2);
        hig2.setBounds(277, 334, 150, 25);

        upa.setText("UPDATE");
        upa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upaActionPerformed(evt);
            }
        });
        jPanel2.add(upa);
        upa.setBounds(240, 400, 100, 21);

        can2.setText("CANCEL");
        can2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                can2ActionPerformed(evt);
            }
        });
        jPanel2.add(can2);
        can2.setBounds(590, 400, 100, 20);

        genderr1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderr1.setToolTipText("CUSTOMER GENDER");
        jPanel2.add(genderr1);
        genderr1.setBounds(280, 140, 150, 25);

        del.setText("DELETE");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel2.add(del);
        del.setBounds(410, 400, 100, 20);

        jLabel11.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("        CUSTOMER MODIFICATION");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(280, 0, 400, 35);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/bca/D_10.jpg"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 200, 500);

        jLabel9.setText("TO");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(450, 220, 17, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rec_num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rec_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rec_num2ActionPerformed

    private void c_lname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_lname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_lname2ActionPerformed

    private void weh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weh2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weh2ActionPerformed

    private void upaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upaActionPerformed
        
      String d1=((JTextField) date3.getDateEditor().getUiComponent()).getText();
      String d2=((JTextField) date4.getDateEditor().getUiComponent()).getText();
      String genn=(String)genderr1.getSelectedItem();
      try{
          int a=JOptionPane.showConfirmDialog(null, "Do You Really Want to UPDATE","UPDATED",JOptionPane.YES_NO_OPTION);
          if(a==0){
          String sql="update customer_details set first_name=?,middle_name=?,last_name=?,gender=?,contact_number=?,date_1=?,date_2=?,age=?,weight=?,hight=? where receipt_number=?";
          ps=co.prepareStatement(sql);
          ps.setString(1, c_fname2.getText());
          ps.setString(2, c_mname2.getText());
          ps.setString(3, c_lname2.getText());
          ps.setString(4, genn);
          ps.setString(5, con_num2.getText());
         ps.setString(6, d1);
        // ps.setString(7, date_5.getText());
            ps.setString(7, d2);
          ps.setString(8, age2.getText());
          ps.setString(9, weh2.getText());
          ps.setString(10, hig2.getText());
          ps.setString(11, rec_num2.getText());
          ps.executeUpdate();
          JOptionPane.showMessageDialog(null, "UPDATED");
      }}
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
      rec_num2.setText("");
      c_fname2.setText("");
      c_mname2.setText("");
      c_lname2.setText("");
      genderr1.setSelectedItem("");
      con_num2.setText("");
      //date_4.setText("");
     // date_5.setText("");
     date3.setDateFormatString("");
     date4.setDateFormatString("");
     age2.setText("");
     weh2.setText("");
     hig2.setText("");
                     
      
    }//GEN-LAST:event_upaActionPerformed

    private void can2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_can2ActionPerformed
        // TODO add your handling code here:
        close();
        home h=new home();
        h.setVisible(true);
    }//GEN-LAST:event_can2ActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
           
      //String d1=((JTextField) date3.getDateEditor().getUiComponent()).getText();
      //String d2=((JTextField) date4.getDateEditor().getUiComponent()).getText();
      String genn=(String) genderr1.getSelectedItem();
        try{
            int a=JOptionPane.showConfirmDialog(null, "Do You Really Want to DELETE","DELETED",JOptionPane.YES_NO_OPTION);
            if(a==0){
             String sql="delete from customer_details where receipt_number=?";
               ps=co.prepareCall(sql);
                ps.setString(1, rec_num2.getText());
                ps.execute();
                JOptionPane.showMessageDialog(null, "DELETED");
        }}
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         rec_num2.setText("");
      c_fname2.setText("");
      c_mname2.setText("");
      c_lname2.setText("");
      genderr1.setSelectedItem("");
      con_num2.setText("");
   //   date_4.setText("");
     // date_5.setText("");
     date3.setDateFormatString("");
      date4.setDateFormatString("");
     age2.setText("");
     weh2.setText("");
     hig2.setText("");
    }//GEN-LAST:event_delActionPerformed

    private void rec_num2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rec_num2KeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_rec_num2KeyTyped

    private void con_num2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_con_num2KeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_con_num2KeyTyped

    private void age2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age2KeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_age2KeyTyped

    private void weh2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weh2KeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_weh2KeyTyped

    private void hig2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hig2KeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_hig2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age2;
    private javax.swing.JTextField c_fname2;
    private javax.swing.JTextField c_lname2;
    private javax.swing.JTextField c_mname2;
    private javax.swing.JButton can2;
    private javax.swing.JTextField con_num2;
    private javax.swing.JButton del;
    private javax.swing.JComboBox<String> genderr1;
    private javax.swing.JTextField hig2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField rec_num2;
    private javax.swing.JButton upa;
    private javax.swing.JTextField weh2;
    // End of variables declaration//GEN-END:variables

}
