/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym.bca;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author KRATOS
 */
public class enq_delete extends javax.swing.JFrame {
Connection co=null;
ResultSet rs=null;
PreparedStatement ps=null;
    /**
     * Creates new form enq_delete
     */
    public enq_delete() {
        initComponents();
         co=Mysqlconnect.MysqlDB();
    }
        public void close(){
        WindowEvent w=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
          Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(w);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emi_fn = new javax.swing.JTextField();
        emi_mn = new javax.swing.JTextField();
        emi_ln = new javax.swing.JTextField();
        emi_aeg = new javax.swing.JTextField();
        emi_con = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        eni_no = new javax.swing.JTextField();
        emi_gen = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emi_date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/bca/P_6.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 950, 110);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CUSTOMER NAME");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(42, 131, 200, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("GENDER");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(42, 174, 200, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("AGE");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(42, 217, 200, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CONTACT NUMBER");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(42, 260, 200, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DATE");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(42, 303, 200, 25);

        emi_fn.setToolTipText("CUSTOMER FIRST NAME");
        jPanel2.add(emi_fn);
        emi_fn.setBounds(260, 131, 150, 25);

        emi_mn.setToolTipText("CUSTOMER MIDDLE NAME");
        jPanel2.add(emi_mn);
        emi_mn.setBounds(428, 131, 150, 25);

        emi_ln.setToolTipText("CUSTOMER LAST NAME");
        jPanel2.add(emi_ln);
        emi_ln.setBounds(596, 131, 150, 25);

        emi_aeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emi_aegKeyTyped(evt);
            }
        });
        jPanel2.add(emi_aeg);
        emi_aeg.setBounds(260, 217, 150, 25);

        emi_con.setToolTipText("CUSTOMER CONTACT NUMBER");
        emi_con.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emi_conKeyTyped(evt);
            }
        });
        jPanel2.add(emi_con);
        emi_con.setBounds(260, 260, 200, 25);

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(268, 382, 100, 20);

        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(494, 382, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("ENQIRY NUMBER");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(42, 88, 200, 25);

        eni_no.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        eni_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eni_noKeyTyped(evt);
            }
        });
        jPanel2.add(eni_no);
        eni_no.setBounds(260, 90, 150, 25);

        emi_gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        emi_gen.setToolTipText("CUSTOMER GENDER");
        jPanel2.add(emi_gen);
        emi_gen.setBounds(260, 174, 150, 25);

        jLabel9.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CUSTOMER ENQUIRY MODIFICATION");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(310, 0, 400, 35);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/bca/D_6.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 200, 500);

        emi_date.setDateFormatString("YYYY-MM-DD");
        jPanel2.add(emi_date);
        emi_date.setBounds(260, 310, 150, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       // String d1=((JTextField) emi_date.getDateEditor().getUiComponent()).getText();
        String genn=(String) emi_gen.getSelectedItem();
        try{
            String sql="delete from enquiry where enquiry_number=?"; 
            ps=co.prepareStatement(sql);
            ps.setString(1, eni_no.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "DELETED");
        }
        
        catch(Exception e){
            
        }
        eni_no.setText("");
        emi_fn.setText("");
        emi_mn.setText("");
        emi_ln.setText("");
        emi_gen.setSelectedItem("");
        emi_aeg.setText("");
        emi_con.setText("");
        emi_date.setDateFormatString("");
        // date_6.setText("");
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        home h=new home();
        h.setVisible(true);
        close();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void eni_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eni_noKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_eni_noKeyTyped

    private void emi_aegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emi_aegKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_emi_aegKeyTyped

    private void emi_conKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emi_conKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_emi_conKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enq_delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enq_delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enq_delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enq_delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enq_delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emi_aeg;
    private javax.swing.JTextField emi_con;
    public static com.toedter.calendar.JDateChooser emi_date;
    private javax.swing.JTextField emi_fn;
    private javax.swing.JComboBox<String> emi_gen;
    private javax.swing.JTextField emi_ln;
    private javax.swing.JTextField emi_mn;
    private javax.swing.JTextField eni_no;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
