/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym.bca;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author KRATOS
 */
public class enquiry extends javax.swing.JFrame {
Connection co=null;
ResultSet rs=null;
PreparedStatement ps=null;
    /**
     * Creates new form enquiry
     */
    public enquiry() {
        initComponents();
         co=Mysqlconnect.MysqlDB();
    }
public void close(){
            WindowEvent ew=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(ew);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        en_no = new javax.swing.JTextField();
        en_fn = new javax.swing.JTextField();
        en_mn = new javax.swing.JTextField();
        en_ln = new javax.swing.JTextField();
        en_gen = new javax.swing.JComboBox<>();
        en_aeg = new javax.swing.JTextField();
        en_con = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        en_date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/bca/P_7.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 950, 110);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ENQIRY NUMBER");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(69, 89, 200, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CUSTOMER NAME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(69, 132, 200, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("GENDER");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(69, 175, 200, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("AGE");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(69, 218, 200, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("CONTACT NUMBER");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(69, 261, 200, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("DATE");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(69, 304, 200, 25);

        en_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                en_noKeyTyped(evt);
            }
        });
        jPanel2.add(en_no);
        en_no.setBounds(287, 89, 150, 25);

        en_fn.setToolTipText("CUSTOMER FIRST NAME\n");
        jPanel2.add(en_fn);
        en_fn.setBounds(287, 132, 150, 25);

        en_mn.setToolTipText("CUSTOMER MIDDLE NAME");
        jPanel2.add(en_mn);
        en_mn.setBounds(478, 132, 150, 25);

        en_ln.setToolTipText("CUSTOMER LAST NAME");
        jPanel2.add(en_ln);
        en_ln.setBounds(669, 132, 150, 25);

        en_gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        en_gen.setToolTipText("CUSTOMER GENDER");
        jPanel2.add(en_gen);
        en_gen.setBounds(287, 175, 150, 25);

        en_aeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                en_aegKeyTyped(evt);
            }
        });
        jPanel2.add(en_aeg);
        en_aeg.setBounds(287, 218, 150, 25);

        en_con.setToolTipText("CUSTOMER CONTACT NUMBER");
        en_con.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                en_conKeyTyped(evt);
            }
        });
        jPanel2.add(en_con);
        en_con.setBounds(287, 261, 200, 25);

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(287, 390, 100, 20);

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(480, 390, 100, 20);

        jLabel9.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CUSTOMER ENQUIRY");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(340, 0, 400, 35);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/bca/D_7.jpg"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 200, 500);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(760, 310, 0, 2);

        en_date.setDateFormatString("YYYY-MM-DD");
        jPanel2.add(en_date);
        en_date.setBounds(290, 310, 150, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      String datee1=((JTextField)en_date.getDateEditor().getUiComponent()).getText();
        String gen=(String) en_gen.getSelectedItem();
        try{
             String sql="insert into enquiry (enquiry_number,first_name,middle_number,last_name,gender,age,contact_number,date_3) values (?,?,?,?,?,?,?,?)";
             ps=co.prepareStatement(sql);
             ps.setString(1, en_no.getText());
             ps.setString(2, en_fn.getText());
             ps.setString(3, en_mn.getText());
             ps.setString(4, en_ln.getText());
             ps.setString(5, gen);
             ps.setString(6, en_aeg.getText());
             ps.setString(7, en_con.getText());
             ps.setString(8, datee1);
        //  ps.setString(8,time2.getText());
        ps.execute();
             JOptionPane.showMessageDialog(null, "SAVED");
             
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        en_no.setText("");
        en_fn.setText("");
        en_mn.setText("");
        en_ln.setText("");
        en_gen.setSelectedItem("");
        en_aeg.setText("");
        en_con.setText("");
       en_date.setDateFormatString("");
         // time2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        home h=new home();
        h.setVisible(true);
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void en_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_en_noKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_en_noKeyTyped

    private void en_aegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_en_aegKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_en_aegKeyTyped

    private void en_conKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_en_conKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_en_conKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enquiry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField en_aeg;
    private javax.swing.JTextField en_con;
    public static com.toedter.calendar.JDateChooser en_date;
    private javax.swing.JTextField en_fn;
    private javax.swing.JComboBox<String> en_gen;
    private javax.swing.JTextField en_ln;
    private javax.swing.JTextField en_mn;
    private javax.swing.JTextField en_no;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
