/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym.bca;
import com.sun.glass.events.KeyEvent;
import static gym.bca.customer1.c_fname;
import static gym.bca.customer1.c_lname;
import static gym.bca.customer1.c_mname;
import static gym.bca.customer1.cont_num;
import static gym.bca.customer1.date11;
import static gym.bca.customer1.date2;
import static gym.bca.customer1.genderr;
import static gym.bca.customer1.hig;
import static gym.bca.customer1.rec1;
import static gym.bca.customer1.weg;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.*;
import java.sql.*;

public class payment extends javax.swing.JFrame {
Connection co=null;
ResultSet rs=null;
PreparedStatement ps=null;
    /**
     * Creates new form payment
     */
    public payment() {
        initComponents();
        co=Mysqlconnect.MysqlDB();
        
    }
       public void close(){
        WindowEvent w=new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
          Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(w);
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        try {
            rec_num3 =(javax.swing.JTextField)java.beans.Beans.instantiate(getClass().getClassLoader(), "gym/bca.payment_rec_num3");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        c_mname3 = new javax.swing.JTextField();
        c_lname3 = new javax.swing.JTextField();
        c_fname3 = new javax.swing.JTextField();
        con_num3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        okk = new javax.swing.JButton();
        can3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        p_type = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/bca/P_5.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 950, 110);

        jPanel2.setLayout(null);

        jLabel1.setText("RECEIPT NUMBER");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(47, 65, 200, 25);

        jLabel2.setText("CUSTOMER NAME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(47, 103, 200, 25);

        jLabel3.setText("CONTACT NUMBER");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(47, 141, 200, 25);

        jLabel4.setText("AMOUNT");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(47, 181, 200, 25);

        rec_num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rec_num3ActionPerformed(evt);
            }
        });
        jPanel2.add(rec_num3);
        rec_num3.setBounds(265, 65, 150, 25);

        c_mname3.setToolTipText("CUSTOMER MIDDLE NAME");
        jPanel2.add(c_mname3);
        c_mname3.setBounds(425, 103, 150, 25);

        c_lname3.setToolTipText("CUSTOMER LAST NAME");
        jPanel2.add(c_lname3);
        c_lname3.setBounds(585, 103, 150, 25);

        c_fname3.setToolTipText("CUSTOMER FIRST NAME");
        c_fname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_fname3ActionPerformed(evt);
            }
        });
        jPanel2.add(c_fname3);
        c_fname3.setBounds(265, 103, 150, 25);

        con_num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_num3ActionPerformed(evt);
            }
        });
        jPanel2.add(con_num3);
        con_num3.setBounds(265, 141, 200, 25);

        jLabel5.setText("PAYMENT TYPE");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(47, 222, 200, 25);

        amt.setToolTipText("Rs.");
        amt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amtKeyTyped(evt);
            }
        });
        jPanel2.add(amt);
        amt.setBounds(265, 179, 150, 25);

        okk.setText("OK");
        okk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okkActionPerformed(evt);
            }
        });
        jPanel2.add(okk);
        okk.setBounds(270, 390, 100, 21);

        can3.setText("CANCEL");
        can3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                can3ActionPerformed(evt);
            }
        });
        jPanel2.add(can3);
        can3.setBounds(480, 390, 100, 21);

        jLabel6.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CUSTOMER PAYMENT");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(320, 0, 400, 35);

        p_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CHEQUE", "DEBIT CARD", "PAYTM" }));
        p_type.setToolTipText("TYPE OF PAYMENT");
        jPanel2.add(p_type);
        p_type.setBounds(265, 222, 150, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym/bca/D_5.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 230, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void con_num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_num3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_num3ActionPerformed

    private void c_fname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_fname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_fname3ActionPerformed

    private void okkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okkActionPerformed
        // TODO add your handling code here:
        
      
      try{
           String type=(String) p_type.getSelectedItem();
           int a;
            a = JOptionPane.showConfirmDialog(null, "Do You Really Want to CONFRIM","CONFORMED",JOptionPane.YES_NO_OPTION);
            if(a==0){
            String sql="insert into  payment (amo,type) values (?,?) ";
            ps=co.prepareStatement(sql);
            ps.setString(1, amt.getText());
            ps.setString(2, type);
            ps.execute();
            JOptionPane.showMessageDialog(null, "CONFORMED");
           
       }}
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       String datee1=((JTextField)date11.getDateEditor().getUiComponent()).getText();
      String datee2=((JTextField)date2.getDateEditor().getUiComponent()).getText();
     
         cust_recipt cr=new cust_recipt();
        cr.r_rec.setText(rec1.getText());
         cr.r_fname.setText(c_fname.getText());
         cr.R_mname.setText(c_mname.getText());
         cr.r_lname.setText(c_lname.getText());
         cr.r_genderr.setText((String) genderr.getSelectedItem());
        cr.r_date1.setText(datee1);
         cr.r_date2.setText(datee2);
         
         cr.r_cont.setText(cont_num.getText());
         cr.r_weg.setText(weg.getText());
         cr.r_hig.setText(hig.getText());
         cr.r_amt.setText(amt.getText());
         cr.r_type.setText((String) p_type.getSelectedItem());
         
         cr.setVisible(true);
          close();
    }//GEN-LAST:event_okkActionPerformed

    private void can3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_can3ActionPerformed
        // TODO add your handling code here:
       int a;
    a = JOptionPane.showConfirmDialog(null, "Do You Really Want to Cancle","Cancel",JOptionPane.YES_NO_OPTION);
    if(a==0){
       close();
        home h=new home();
        h.setVisible(true);
        
    }
    }//GEN-LAST:event_can3ActionPerformed

    private void rec_num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rec_num3ActionPerformed
        // TODO add your handling code here:
     
     
      
                
    }//GEN-LAST:event_rec_num3ActionPerformed

    private void amtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amtKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE){
            evt.consume();
            
        }
    }//GEN-LAST:event_amtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField amt;
    public static javax.swing.JTextField c_fname3;
    public static javax.swing.JTextField c_lname3;
    public static javax.swing.JTextField c_mname3;
    private javax.swing.JButton can3;
    public static javax.swing.JTextField con_num3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton okk;
    public static javax.swing.JComboBox<String> p_type;
    public static javax.swing.JTextField rec_num3;
    // End of variables declaration//GEN-END:variables

}
